# Base BotClean solution based on minimal distance movement
BOT_CLEAN := src/BotClean_minDistance.py

UNITTEST_EXE := python -m unittest

test_next_move_BasicMovement:
	$(UNITTEST_EXE) tst.test_BotClean_minDistance.next_move_BasicMovement


